"""
AI-Written Text Detector
Detects if email body was generated by an LLM (GPT, Claude, etc.)
Uses statistical NLP: perplexity, burstiness, entropy analysis
Author: Omar Tamer
"""

import re
import math
import string
from typing import Dict, Any, List
from collections import Counter


class AITextDetector:
    """
    Detects AI-generated text using multiple statistical signals:
    1. Perplexity — AI text has low perplexity (more predictable)
    2. Burstiness — Human text varies sentence length more (high burstiness)
    3. Vocabulary richness — AI uses broader, more formal vocabulary
    4. Phrase patterns — GPT-style connectors & transitions
    5. Punctuation patterns — AI overuses certain punctuation styles
    """

    AI_PHRASES = [
        "please note that", "it is important to", "as soon as possible",
        "we would like to inform", "kindly", "please be advised",
        "we are writing to", "please find attached", "do not hesitate",
        "should you have any questions", "thank you for your understanding",
        "rest assured", "we sincerely apologize", "in order to",
        "for your convenience", "we would like to remind",
        "please ensure that", "we appreciate your", "as per our records",
        "for security purposes", "to protect your account",
        "we have detected unusual", "your account security",
        "verify your identity", "click the link below",
        "failure to comply", "take immediate action"
    ]

    HUMAN_CONTRACTIONS = [
        "i'm", "you're", "we're", "they're", "i've", "you've",
        "i'll", "you'll", "can't", "won't", "don't", "isn't",
        "wasn't", "didn't", "haven't", "wouldn't", "couldn't"
    ]

    def analyze(self, text: str) -> Dict[str, Any]:
        if not text or len(text.strip()) < 50:
            return {
                "ai_score": 0,
                "verdict": "INSUFFICIENT_TEXT",
                "signals": {},
                "explanation": "Text too short for analysis"
            }

        signals = {
            "perplexity": self._calculate_perplexity(text),
            "burstiness": self._calculate_burstiness(text),
            "ai_phrases": self._detect_ai_phrases(text),
            "vocabulary_richness": self._calculate_vocabulary_richness(text),
            "sentence_uniformity": self._calculate_sentence_uniformity(text),
            "formality_score": self._calculate_formality(text),
            "contraction_ratio": self._calculate_contraction_ratio(text),
            "avg_sentence_length": self._avg_sentence_length(text),
            "punctuation_pattern": self._analyze_punctuation(text)
        }

        ai_score, explanation = self._calculate_ai_score(signals, text)

        if ai_score >= 75:
            verdict = "LIKELY_AI_GENERATED"
        elif ai_score >= 50:
            verdict = "POSSIBLY_AI_GENERATED"
        elif ai_score >= 25:
            verdict = "UNCERTAIN"
        else:
            verdict = "LIKELY_HUMAN_WRITTEN"

        return {
            "ai_score": ai_score,
            "verdict": verdict,
            "confidence": self._get_confidence_label(ai_score),
            "signals": signals,
            "explanation": explanation,
            "ai_phrases_found": self._get_found_phrases(text)
        }

    def _calculate_perplexity(self, text: str) -> float:
        """
        Approximates perplexity using bigram entropy.
        AI text tends to have lower perplexity (more predictable patterns).
        Returns normalized score 0-1 where low = AI-like.
        """
        words = self._tokenize(text)
        if len(words) < 10:
            return 0.5

        bigrams = list(zip(words[:-1], words[1:]))
        bigram_counts = Counter(bigrams)
        word_counts = Counter(words)

        entropy = 0
        for bigram, count in bigram_counts.items():
            p_bigram = count / len(bigrams)
            entropy -= p_bigram * math.log2(p_bigram + 1e-10)

        # Normalize: typical human text entropy 8-12, AI 4-8
        normalized = min(entropy / 12.0, 1.0)
        return round(normalized, 3)

    def _calculate_burstiness(self, text: str) -> float:
        """
        Burstiness = variation in sentence lengths.
        Human text is more 'bursty' (varies more).
        AI text tends to have consistent sentence lengths.
        Returns 0-1 where low = AI-like (uniform sentences).
        """
        sentences = self._split_sentences(text)
        if len(sentences) < 3:
            return 0.5

        lengths = [len(s.split()) for s in sentences if s.strip()]
        if not lengths:
            return 0.5

        mean = sum(lengths) / len(lengths)
        if mean == 0:
            return 0.5

        variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
        std_dev = math.sqrt(variance)
        cv = std_dev / mean  # Coefficient of variation

        # High CV = human, Low CV = AI
        return round(min(cv, 1.0), 3)

    def _detect_ai_phrases(self, text: str) -> float:
        """Returns ratio of AI-style phrases found."""
        text_lower = text.lower()
        found = sum(1 for phrase in self.AI_PHRASES if phrase in text_lower)
        return round(found / len(self.AI_PHRASES), 3)

    def _calculate_vocabulary_richness(self, text: str) -> float:
        """Type-Token Ratio: unique words / total words. AI text tends higher."""
        words = self._tokenize(text)
        if not words:
            return 0
        unique = len(set(words))
        ttr = unique / len(words)
        return round(ttr, 3)

    def _calculate_sentence_uniformity(self, text: str) -> float:
        """How uniform are sentences in structure? AI = more uniform."""
        sentences = self._split_sentences(text)
        if len(sentences) < 3:
            return 0.5

        lengths = [len(s.split()) for s in sentences if s.strip()]
        if not lengths:
            return 0.5

        mean = sum(lengths) / len(lengths)
        variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
        std_dev = math.sqrt(variance)

        # Low std_dev relative to mean = uniform = AI
        cv = std_dev / (mean + 1e-10)
        uniformity = max(0, 1 - cv)
        return round(uniformity, 3)

    def _calculate_formality(self, text: str) -> float:
        """Formal language score — AI tends to be more formal."""
        formal_words = [
            "therefore", "furthermore", "additionally", "consequently",
            "nevertheless", "regarding", "pursuant", "hereby", "thereof",
            "henceforth", "aforementioned", "subsequently", "accordingly"
        ]
        informal_words = [
            "yeah", "ok", "hey", "gonna", "wanna", "kinda", "sorta",
            "btw", "lol", "omg", "tbh", "imo", "ngl"
        ]

        words = self._tokenize(text)
        if not words:
            return 0.5

        formal_count = sum(1 for w in words if w in formal_words)
        informal_count = sum(1 for w in words if w in informal_words)

        ratio = (formal_count + 1) / (informal_count + formal_count + 1)
        return round(ratio, 3)

    def _calculate_contraction_ratio(self, text: str) -> float:
        """AI text uses fewer contractions. Low ratio = more AI-like."""
        text_lower = text.lower()
        words = self._tokenize(text)
        if not words:
            return 0

        contraction_count = sum(1 for c in self.HUMAN_CONTRACTIONS if c in text_lower)
        ratio = contraction_count / (len(words) + 1)
        return round(ratio, 4)

    def _avg_sentence_length(self, text: str) -> float:
        sentences = self._split_sentences(text)
        if not sentences:
            return 0
        lengths = [len(s.split()) for s in sentences if s.strip()]
        return round(sum(lengths) / len(lengths), 1) if lengths else 0

    def _analyze_punctuation(self, text: str) -> Dict:
        return {
            "exclamation_ratio": text.count("!") / (len(text) + 1),
            "comma_ratio": text.count(",") / (len(text) + 1),
            "ellipsis_count": text.count("...")
        }

    def _calculate_ai_score(self, signals: Dict, text: str) -> tuple:
        score = 0
        reasons = []

        # Low burstiness = uniform sentences = AI signal
        if signals["burstiness"] < 0.3:
            score += 25
            reasons.append("Very uniform sentence lengths (low burstiness)")
        elif signals["burstiness"] < 0.5:
            score += 12

        # Low perplexity = predictable text = AI signal
        if signals["perplexity"] < 0.4:
            score += 20
            reasons.append("Low text perplexity (highly predictable patterns)")
        elif signals["perplexity"] < 0.6:
            score += 10

        # High AI phrase ratio
        if signals["ai_phrases"] > 0.15:
            score += 25
            reasons.append(f"Multiple AI/template phrases detected ({int(signals['ai_phrases']*100)}%)")
        elif signals["ai_phrases"] > 0.08:
            score += 12

        # High uniformity
        if signals["sentence_uniformity"] > 0.7:
            score += 15
            reasons.append("Highly uniform sentence structure")

        # High formality, low contractions
        if signals["formality_score"] > 0.8 and signals["contraction_ratio"] < 0.01:
            score += 15
            reasons.append("Formal language with no contractions (AI writing style)")

        explanation = " | ".join(reasons) if reasons else "No strong AI indicators found"
        return min(score, 100), explanation

    def _get_found_phrases(self, text: str) -> List[str]:
        text_lower = text.lower()
        return [phrase for phrase in self.AI_PHRASES if phrase in text_lower]

    def _get_confidence_label(self, score: int) -> str:
        if score >= 85:
            return "Very High"
        elif score >= 65:
            return "High"
        elif score >= 45:
            return "Medium"
        elif score >= 25:
            return "Low"
        return "Very Low"

    def _tokenize(self, text: str) -> List[str]:
        text = text.lower()
        text = text.translate(str.maketrans("", "", string.punctuation))
        return [w for w in text.split() if w]

    def _split_sentences(self, text: str) -> List[str]:
        sentences = re.split(r'[.!?]+', text)
        return [s.strip() for s in sentences if s.strip()]
